String censorMessage(String message) {
  List<String> bannedWords = [
    "dumb",
    "stupid",
    "bitch",
    "idiot",
    "fool",
    "jerk",
    "moron",
    "asshole",
    "bastard",
    "shit",
    "damn",
    "fuck",
    "motherfucker",
    "cunt",
    "ass",
    "prick",
    "twat",
    "dick",
    "cock",
    "pussy",
    "slut",
    "whore",
    "crap",
    "arse",
    "bollocks",
    "bugger",
    "git",
    "wanker",
    "tosser",
    "sod",
    "bloody",
    "shag",
    "douche",
    "skank",
    "retard",
    "spaz",
    "gimp",
    "nonce",
    "tosspot",
    "twat",
    "minger",
    "numpty",
    "plonker",
    "bellend",
    "knob",
    "knobhead",
    "wazzock"
  ];

  List<String> bannedWordsArabic = [
    "غبي",
    "أحمق",
    "بلهاء",
    "قذر",
    "خنزير",
    "لعنة",
    "تباً",
    "تافه",
    "حمار",
    "حيوان",
    "سافل",
    "حقير",
    "وضيع",
    "كلب",
    "ابن كلب",
    "قحبة",
    "شرموطة",
    "عاهرة",
    "لوطي",
    "زاني",
    "مومس",
    "شرموط",
    "خنيث",
    "ديوث",
    "بغل",
    "معتوه",
    "مخبول",
    "مختل",
    "أهبل",
    "مغفل",
    "مغفلة",
    "مجروح",
    "حقيرة",
    "كريه",
    "ملعون",
    "مزعج",
    "مضطرب",
    "معتدي",
    "مجنون",
    "موسوس",
    "مهوس",
    "مهمل",
    "عديم الفائدة",
    "عديم الفائدة",
    "عديم الاحترام",
    "عديم الأخلاق",
    "عديم الشرف"
  ];

  List<String> allBannedWords = bannedWords + bannedWordsArabic;
  String censoredMessage = message;
  for (String word in allBannedWords) {
    String replacement = '*' * word.length;
    censoredMessage = censoredMessage.replaceAll(
        RegExp('\\b' + word + '\\b', caseSensitive: false), replacement);
  }
  return censoredMessage;
}
